# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1253efKdSF6o4LA_0kJ8jNwlF8k9yg_Cf
"""

class Calificaciones:
    def leer_datos(self):
        self.nombres = []
        self.notas = []
        for i in range(10):
            nombre = input("Ingrese el nombre del alumno: ")
            nota = float(input("Ingrese la calificación del alumno: "))
            self.nombres.append(nombre)
            self.notas.append(nota)

    def procesar(self):
        self.promedio_grupal = sum(self.notas) / len(self.notas)
        self.alumnos_excelentes = []
        for i in range(len(self.notas)):
            if self.notas[i] > 9.5:
                self.alumnos_excelentes.append(self.nombres[i])

    def imprimir_resultados(self):
        print("\n--- RESULTADOS ---")
        print("Promedio grupal:", self.promedio_grupal)
        print("Alumnos con calificación mayor a 9.5:")
        for alumno in self.alumnos_excelentes:
            print("-", alumno)


grupo = Calificaciones()
grupo.leer_datos()
grupo.procesar()
grupo.imprimir_resultados()