# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d77inUInFYIuFMypVfahCNYAA7Hy5aoP
"""

class Triangulo:
    base = 0
    altura = 0

    def pedir_datos(self):
        self.base = int(input("Escribe la base del triángulo: "))
        self.altura = int(input("Escribe la altura del triángulo: "))

    def obtener_area(self):
        return (self.base * self.altura) / 2

    def mostrar_area(self):
        area = self.obtener_area()
        print("El área del triángulo es:", area)

tri = Triangulo()

tri.pedir_datos()
tri.mostrar_area()